// Compilable usage examples for runtime backup operations.
// These examples are type-checked during build to guard against API regressions.
using Camunda.Orchestration.Sdk;

public static class BackupExamples
{
    #region TakeRuntimeBackup
    // <TakeRuntimeBackup>
    public static async Task TakeRuntimeBackupExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        // Omit `BackupId` when continuous backups or a backup/checkpoint schedule is
        // enabled for the physical tenant — the id is then generated by the cluster.
        // Otherwise `BackupId` is required and must be higher than any existing one.
        var backup = await client.TakeRuntimeBackupAsync(
            new TakeRuntimeBackupRequest { BackupId = backupId });

        Console.WriteLine($"Scheduled backup {backup.BackupId}");
    }
    // </TakeRuntimeBackup>
    #endregion TakeRuntimeBackup

    #region ListRuntimeBackups

    // <ListRuntimeBackups>
    public static async Task ListRuntimeBackupsExample()
    {
        using var client = CamundaClient.Create();

        // `prefix` must end in a single '*'. Omit it to list every backup.
        var backups = await client.ListRuntimeBackupsAsync(
            BackupIdPrefix.AssumeExists("10*"));

        Console.WriteLine($"Runtime backups: {backups}");
    }
    // </ListRuntimeBackups>
    #endregion ListRuntimeBackups

    #region GetRuntimeBackup

    // <GetRuntimeBackup>
    public static async Task GetRuntimeBackupExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        var backup = await client.GetRuntimeBackupAsync(backupId);

        Console.WriteLine($"Backup {backup.BackupId}: {backup.State}");
        foreach (var partition in backup.Details)
        {
            Console.WriteLine($"  Partition {partition.PartitionId}: {partition.State}");
        }
    }
    // </GetRuntimeBackup>
    #endregion GetRuntimeBackup

    #region DeleteRuntimeBackup

    // <DeleteRuntimeBackup>
    public static async Task DeleteRuntimeBackupExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        await client.DeleteRuntimeBackupAsync(backupId);
    }
    // </DeleteRuntimeBackup>
    #endregion DeleteRuntimeBackup

    #region GetRuntimeBackupState

    // <GetRuntimeBackupState>
    public static async Task GetRuntimeBackupStateExample()
    {
        using var client = CamundaClient.Create();

        var state = await client.GetRuntimeBackupStateAsync();

        foreach (var checkpoint in state.CheckpointStates)
        {
            Console.WriteLine(
                $"Partition {checkpoint.PartitionId} checkpoint {checkpoint.CheckpointId} ({checkpoint.CheckpointType})");
        }
        foreach (var range in state.Ranges)
        {
            Console.WriteLine(
                $"Partition {range.PartitionId} range: {range.Start?.CheckpointId} -> {range.End?.CheckpointId}");
        }
    }
    // </GetRuntimeBackupState>
    #endregion GetRuntimeBackupState

    #region SyncRuntimeBackupState

    // <SyncRuntimeBackupState>
    public static async Task SyncRuntimeBackupStateExample()
    {
        using var client = CamundaClient.Create();

        // Force-writes checkpoint and backup metadata of every partition to the backup
        // store, independent of any backup being taken, and returns the updated state.
        var state = await client.SyncRuntimeBackupStateAsync();

        Console.WriteLine($"Synced {state.BackupStates.Count} partition backup states");
    }
    // </SyncRuntimeBackupState>
    #endregion SyncRuntimeBackupState

    #region DeleteRuntimeBackupState

    // <DeleteRuntimeBackupState>
    public static async Task DeleteRuntimeBackupStateExample()
    {
        using var client = CamundaClient.Create();

        // Clears all checkpoint info, backup info, checkpoint metadata, and backup
        // ranges on every partition. Used when switching backup stores.
        await client.DeleteRuntimeBackupStateAsync();
    }
    // </DeleteRuntimeBackupState>
    #endregion DeleteRuntimeBackupState
}
