// Compilable usage examples for runtime backup operations.
// These examples are type-checked during build to guard against API regressions.
using Camunda.Orchestration.Sdk;

public static class BackupExamples
{
    #region TakeRuntimeBackup
    // <TakeRuntimeBackup>
    public static async Task TakeRuntimeBackupExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        // Omit `BackupId` when continuous backups or a backup/checkpoint schedule is
        // enabled for the physical tenant — the id is then generated by the cluster.
        // Otherwise `BackupId` is required and must be higher than any existing one.
        var backup = await client.TakeRuntimeBackupAsync(
            new TakeRuntimeBackupRequest { BackupId = backupId });

        Console.WriteLine($"Scheduled backup {backup.BackupId}");
    }
    // </TakeRuntimeBackup>
    #endregion TakeRuntimeBackup

    #region ListRuntimeBackups

    // <ListRuntimeBackups>
    public static async Task ListRuntimeBackupsExample()
    {
        using var client = CamundaClient.Create();

        // `prefix` must end in a single '*'. Omit it to list every backup.
        var backups = await client.ListRuntimeBackupsAsync(
            BackupIdPrefix.AssumeExists("10*"));

        Console.WriteLine($"Runtime backups: {backups}");
    }
    // </ListRuntimeBackups>
    #endregion ListRuntimeBackups

    #region GetRuntimeBackup

    // <GetRuntimeBackup>
    public static async Task GetRuntimeBackupExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        var backup = await client.GetRuntimeBackupAsync(backupId);

        Console.WriteLine($"Backup {backup.BackupId}: {backup.State}");
        foreach (var partition in backup.Details)
        {
            Console.WriteLine($"  Partition {partition.PartitionId}: {partition.State}");
        }
    }
    // </GetRuntimeBackup>
    #endregion GetRuntimeBackup

    #region DeleteRuntimeBackup

    // <DeleteRuntimeBackup>
    public static async Task DeleteRuntimeBackupExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        await client.DeleteRuntimeBackupAsync(backupId);
    }
    // </DeleteRuntimeBackup>
    #endregion DeleteRuntimeBackup

    #region GetRuntimeBackupState

    // <GetRuntimeBackupState>
    public static async Task GetRuntimeBackupStateExample()
    {
        using var client = CamundaClient.Create();

        var state = await client.GetRuntimeBackupStateAsync();

        foreach (var checkpoint in state.CheckpointStates)
        {
            Console.WriteLine(
                $"Partition {checkpoint.PartitionId} checkpoint {checkpoint.CheckpointId} ({checkpoint.CheckpointType})");
        }
        foreach (var range in state.Ranges)
        {
            Console.WriteLine(
                $"Partition {range.PartitionId} range: {range.Start?.CheckpointId} -> {range.End?.CheckpointId}");
        }
    }
    // </GetRuntimeBackupState>
    #endregion GetRuntimeBackupState

    #region SyncRuntimeBackupState

    // <SyncRuntimeBackupState>
    public static async Task SyncRuntimeBackupStateExample()
    {
        using var client = CamundaClient.Create();

        // Force-writes checkpoint and backup metadata of every partition to the backup
        // store, independent of any backup being taken, and returns the updated state.
        var state = await client.SyncRuntimeBackupStateAsync();

        Console.WriteLine($"Synced {state.BackupStates.Count} partition backup states");
    }
    // </SyncRuntimeBackupState>
    #endregion SyncRuntimeBackupState

    #region DeleteRuntimeBackupState

    // <DeleteRuntimeBackupState>
    public static async Task DeleteRuntimeBackupStateExample()
    {
        using var client = CamundaClient.Create();

        // Clears all checkpoint info, backup info, checkpoint metadata, and backup
        // ranges on every partition. Used when switching backup stores.
        await client.DeleteRuntimeBackupStateAsync();
    }
    // </DeleteRuntimeBackupState>
    #endregion DeleteRuntimeBackupState

    #region TakeHistoryBackup

    // <TakeHistoryBackup>
    public static async Task TakeHistoryBackupExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        // Backups are logically ordered by id, so each successive backup must use a
        // higher id than the previous one.
        var backup = await client.TakeHistoryBackupAsync(
            new TakeHistoryBackupRequest { BackupId = backupId });

        Console.WriteLine($"Scheduled history backup {backup.BackupId}");
        foreach (var snapshot in backup.ScheduledSnapshots)
        {
            Console.WriteLine($"  {snapshot}");
        }
    }
    // </TakeHistoryBackup>
    #endregion TakeHistoryBackup

    #region ListHistoryBackups

    // <ListHistoryBackups>
    public static async Task ListHistoryBackupsExample()
    {
        using var client = CamundaClient.Create();

        // `prefix` must end in a single '*'. Omit it to list every history backup.
        var backups = await client.ListHistoryBackupsAsync(
            BackupIdPrefix.AssumeExists("10*"));

        Console.WriteLine($"History backups: {backups}");
    }
    // </ListHistoryBackups>
    #endregion ListHistoryBackups

    #region GetHistoryBackup

    // <GetHistoryBackup>
    public static async Task GetHistoryBackupExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        var backup = await client.GetHistoryBackupAsync(backupId);

        // The aggregated state is derived from the state of every expected snapshot.
        Console.WriteLine($"History backup {backup.BackupId}: {backup.State}");
    }
    // </GetHistoryBackup>
    #endregion GetHistoryBackup

    #region DeleteHistoryBackup

    // <DeleteHistoryBackup>
    public static async Task DeleteHistoryBackupExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        await client.DeleteHistoryBackupAsync(backupId);
    }
    // </DeleteHistoryBackup>
    #endregion DeleteHistoryBackup

    #region TakeHistoryBackupAsClusterAdmin

    // <TakeHistoryBackupAsClusterAdmin>
    public static async Task TakeHistoryBackupAsClusterAdminExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        // Takes a history backup across all physical tenants in the cluster.
        // Backups are logically ordered by id, so each successive backup must use a
        // higher id than the previous one.
        var backup = await client.TakeHistoryBackupAsClusterAdminAsync(
            new TakeHistoryBackupRequest { BackupId = backupId });

        Console.WriteLine($"Scheduled cluster history backup {backup.BackupId}");
        foreach (var tenant in backup.PhysicalTenants)
        {
            Console.WriteLine($"  Tenant {tenant.PhysicalTenantId}: scheduled {tenant.ScheduledSnapshots?.Count} snapshot(s)");
        }
    }
    // </TakeHistoryBackupAsClusterAdmin>
    #endregion TakeHistoryBackupAsClusterAdmin

    #region ListHistoryBackupsAsClusterAdmin

    // <ListHistoryBackupsAsClusterAdmin>
    public static async Task ListHistoryBackupsAsClusterAdminExample()
    {
        using var client = CamundaClient.Create();

        // `prefix` must end in a single '*'. Omit it to list every history backup across all tenants.
        var backups = await client.ListHistoryBackupsAsClusterAdminAsync(
            prefix: BackupIdPrefix.AssumeExists("10*"));

        Console.WriteLine($"Cluster history backups: {backups}");
    }
    // </ListHistoryBackupsAsClusterAdmin>
    #endregion ListHistoryBackupsAsClusterAdmin

    #region GetHistoryBackupAsClusterAdmin

    // <GetHistoryBackupAsClusterAdmin>
    public static async Task GetHistoryBackupAsClusterAdminExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        var backup = await client.GetHistoryBackupAsClusterAdminAsync(backupId);

        Console.WriteLine($"Cluster history backup {backup.BackupId}");
        foreach (var tenant in backup.PhysicalTenants)
        {
            Console.WriteLine($"  Tenant {tenant.PhysicalTenantId}: {tenant.State}");
        }
    }
    // </GetHistoryBackupAsClusterAdmin>
    #endregion GetHistoryBackupAsClusterAdmin

    #region DeleteHistoryBackupAsClusterAdmin

    // <DeleteHistoryBackupAsClusterAdmin>
    public static async Task DeleteHistoryBackupAsClusterAdminExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        await client.DeleteHistoryBackupAsClusterAdminAsync(backupId);
    }
    // </DeleteHistoryBackupAsClusterAdmin>
    #endregion DeleteHistoryBackupAsClusterAdmin

    #region TakeRuntimeBackupAsClusterAdmin

    // <TakeRuntimeBackupAsClusterAdmin>
    public static async Task TakeRuntimeBackupAsClusterAdminExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        // Takes a runtime backup across all physical tenants in the cluster.
        // Omit `BackupId` when continuous backups or a backup/checkpoint schedule is
        // enabled — the id is then generated per tenant. Otherwise it must be higher
        // than any existing backup id on every targeted tenant.
        var backup = await client.TakeRuntimeBackupAsClusterAdminAsync(
            new TakeRuntimeBackupRequest { BackupId = backupId });

        Console.WriteLine($"Triggered cluster runtime backup across {backup.PhysicalTenants.Count} tenant(s)");
        foreach (var tenant in backup.PhysicalTenants)
        {
            if (tenant.BackupId.HasValue)
            {
                Console.WriteLine($"  Tenant {tenant.PhysicalTenantId}: triggered, backup id {tenant.BackupId.Value}");
            }
            else
            {
                Console.WriteLine($"  Tenant {tenant.PhysicalTenantId}: {tenant.Outcome}" +
                    (tenant.Reason != null ? $" — {tenant.Reason}" : ""));
            }
        }
    }
    // </TakeRuntimeBackupAsClusterAdmin>
    #endregion TakeRuntimeBackupAsClusterAdmin

    #region ListRuntimeBackupsAsClusterAdmin

    // <ListRuntimeBackupsAsClusterAdmin>
    public static async Task ListRuntimeBackupsAsClusterAdminExample()
    {
        using var client = CamundaClient.Create();

        // `prefix` must end in a single '*'. Omit it to list every runtime backup across all tenants.
        var backups = await client.ListRuntimeBackupsAsClusterAdminAsync(
            prefix: BackupIdPrefix.AssumeExists("10*"));

        Console.WriteLine($"Cluster runtime backups: {backups}");
    }
    // </ListRuntimeBackupsAsClusterAdmin>
    #endregion ListRuntimeBackupsAsClusterAdmin

    #region GetRuntimeBackupAsClusterAdmin

    // <GetRuntimeBackupAsClusterAdmin>
    public static async Task GetRuntimeBackupAsClusterAdminExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        var backup = await client.GetRuntimeBackupAsClusterAdminAsync(backupId);

        Console.WriteLine($"Cluster runtime backup {backup.BackupId}: {backup.State}");
        if (backup.FailureReason != null)
        {
            Console.WriteLine($"  Failure: {backup.FailureReason}");
        }
    }
    // </GetRuntimeBackupAsClusterAdmin>
    #endregion GetRuntimeBackupAsClusterAdmin

    #region DeleteRuntimeBackupAsClusterAdmin

    // <DeleteRuntimeBackupAsClusterAdmin>
    public static async Task DeleteRuntimeBackupAsClusterAdminExample(BackupId backupId)
    {
        using var client = CamundaClient.Create();

        await client.DeleteRuntimeBackupAsClusterAdminAsync(backupId);
    }
    // </DeleteRuntimeBackupAsClusterAdmin>
    #endregion DeleteRuntimeBackupAsClusterAdmin

    #region GetRuntimeBackupStateAsClusterAdmin

    // <GetRuntimeBackupStateAsClusterAdmin>
    public static async Task GetRuntimeBackupStateAsClusterAdminExample()
    {
        using var client = CamundaClient.Create();

        var state = await client.GetRuntimeBackupStateAsClusterAdminAsync();

        foreach (var tenant in state.PhysicalTenants)
        {
            Console.WriteLine($"Tenant {tenant.PhysicalTenantId}: {tenant.State.CheckpointStates?.Count} checkpoint state(s)");
        }
    }
    // </GetRuntimeBackupStateAsClusterAdmin>
    #endregion GetRuntimeBackupStateAsClusterAdmin

    #region SyncRuntimeBackupStateAsClusterAdmin

    // <SyncRuntimeBackupStateAsClusterAdmin>
    public static async Task SyncRuntimeBackupStateAsClusterAdminExample()
    {
        using var client = CamundaClient.Create();

        // Force-writes checkpoint and backup metadata for every partition of every
        // physical tenant in the cluster to the backup store, and returns the updated state.
        var state = await client.SyncRuntimeBackupStateAsClusterAdminAsync();

        Console.WriteLine($"Synced runtime backup state for {state.PhysicalTenants.Count} tenant(s)");
    }
    // </SyncRuntimeBackupStateAsClusterAdmin>
    #endregion SyncRuntimeBackupStateAsClusterAdmin

    #region DeleteRuntimeBackupStateAsClusterAdmin

    // <DeleteRuntimeBackupStateAsClusterAdmin>
    public static async Task DeleteRuntimeBackupStateAsClusterAdminExample()
    {
        using var client = CamundaClient.Create();

        // Clears all checkpoint info, backup info, checkpoint metadata, and backup
        // ranges on every partition of every physical tenant in the cluster. Used
        // when switching backup stores.
        await client.DeleteRuntimeBackupStateAsClusterAdminAsync();
    }
    // </DeleteRuntimeBackupStateAsClusterAdmin>
    #endregion DeleteRuntimeBackupStateAsClusterAdmin
}
