#!/bin/bash
set -e

# Define paths
SOURCE_DIR=tmp-connectors/
DOCUSAURUS_BASE_URL="https://docs.camunda.io/"

mkdir $SOURCE_DIR
cd "$SOURCE_DIR" || exit 1

git clone https://github.com/camunda/connectors.git # when running locally, replace with: cp path/to/your/local/connectors/ ./connectors -r


cd connectors

# Temp docs file to store extracted links
TMP_FILE="connector-template-links.md"
> "$TMP_FILE"

printf -- "---\n\
id: connector-template-links\n\
title: Connector template links check\n\
hide_title: true\n\
unlisted: true\n\
sidebar_class_name: hidden\n\
---\n\n\
# This page is autogenerated and contains all links the connector template refer to:\n\n" > "$TMP_FILE"

echo "extracting links..."

# Function to extract links from JSON files
extract_links() {
  local file_path="$1"
  local file_name
  file_name=$(basename "$file_path")

  grep -oE "\"$DOCUSAURUS_BASE_URL[^\"]+\"" "$file_path" | sed 's/"//g' | sed 's/[\/\\]*$//' | sed "s|https://docs.camunda.io|[$file_path](|; s|$|)|"
}

# Call extract links on all json file links in connectors repo
find . -type d -name "element-templates" | while read -r dir; do
  find "$dir" -type f -name "*.json" | while read -r file; do
    extract_links "$file"
  done
done | sort -u >> "$TMP_FILE"  # Sort & remove duplicates before writing

mv connector-template-links.md ${GITHUB_WORKSPACE}/docs/components/connectors/ # when running locally, replace with: mv connector-template-links.md ../../docs/components/connectors/

echo "cleaning up..."

cd ../..
rm -rf $SOURCE_DIR

echo "Script completed successfully."
exit 0



