/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  "Frontend development": [
    {
      type: "autogenerated",
      dirName: "apis-tools/frontend-development",
    },
  ],
};
