# Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
# one or more contributor license agreements. See the NOTICE file distributed
# with this work for additional information regarding copyright ownership.
# Licensed under the Camunda License 1.0. You may not use this file
# except in compliance with the Camunda License 1.0.

openapi: 3.0.3
info:
  title: Hub Public API V2
  description: API for communicating with Camunda Hub.
  version: 0.1.0
  contact:
    name: Camunda
    url: https://camunda.com

servers:
  - url: "{schema}://{host}:{port}/api/v2"
    variables:
      host:
        default: localhost
        description: The hostname of the Hub API server.
      port:
        default: "8088"
        description: The port of the Hub API server.
      schema:
        default: http
        description: The schema of the Hub API server.

security:
  - bearerAuth: []

tags:
  - name: Catalog
    description: Catalog asset management operations.
  - name: File
    description: File management operations.
  - name: Folder
    description: Folder management operations.
  - name: Info
    description: API metadata operations.
  - name: Project
    description: Project management operations.
  - name: Version
    description: Version management operations.
  - name: Workspace
    description: Workspace management operations.
  - name: Collaborator
    description: Collaborator management operations.

paths:
  /catalog/assets/ingestion:
    $ref: "catalog.yaml#/paths/~1catalog~1assets~1ingestion"
  /catalog/assets/{assetKey}:
    $ref: "catalog.yaml#/paths/~1catalog~1assets~1{assetKey}"
  /files:
    $ref: "files.yaml#/paths/~1files"
  /files/{fileKey}:
    $ref: "files.yaml#/paths/~1files~1{fileKey}"
  /files/search:
    $ref: "files.yaml#/paths/~1files~1search"
  /folders:
    $ref: "folders.yaml#/paths/~1folders"
  /folders/{folderKey}:
    $ref: "folders.yaml#/paths/~1folders~1{folderKey}"
  /info:
    $ref: "info.yaml#/paths/~1info"
  /projects:
    $ref: "projects.yaml#/paths/~1projects"
  /projects/{projectKey}:
    $ref: "projects.yaml#/paths/~1projects~1{projectKey}"
  /projects/search:
    $ref: "projects.yaml#/paths/~1projects~1search"
  /versions:
    $ref: "versions.yaml#/paths/~1versions"
  /versions/{versionKey}:
    $ref: "versions.yaml#/paths/~1versions~1{versionKey}"
  /versions/search:
    $ref: "versions.yaml#/paths/~1versions~1search"
  /versions/{versionKey}/restoration:
    $ref: "versions.yaml#/paths/~1versions~1{versionKey}~1restoration"
  /workspaces:
    $ref: "workspaces.yaml#/paths/~1workspaces"
  /workspaces/{workspaceKey}:
    $ref: "workspaces.yaml#/paths/~1workspaces~1{workspaceKey}"
  /workspaces/search:
    $ref: "workspaces.yaml#/paths/~1workspaces~1search"
  /workspaces/{workspaceKey}/collaborators:
    $ref: "collaborators.yaml#/paths/~1workspaces~1{workspaceKey}~1collaborators"
  /workspaces/{workspaceKey}/collaborators/{email}:
    $ref: "collaborators.yaml#/paths/~1workspaces~1{workspaceKey}~1collaborators~1{email}"
  /collaborators/search:
    $ref: "collaborators.yaml#/paths/~1collaborators~1search"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from the authorization server.
