// Compilable usage examples for runtime backup operations.
// These examples are type-checked during build to guard against API regressions.

import { createCamundaClient } from '@camunda8/orchestration-cluster-api';

//#region TakeRuntimeBackup
async function takeRuntimeBackupExample() {
  const camunda = createCamundaClient();

  // Omit `backupId` when continuous backups or a backup/checkpoint schedule is
  // enabled for the physical tenant — the id is then generated by the cluster.
  // Otherwise `backupId` is required and must be higher than any existing one.
  const backup = await camunda.takeRuntimeBackup({ backupId: 100 });

  console.log(`Scheduled backup ${backup.backupId}`);
}
//#endregion TakeRuntimeBackup

//#region ListRuntimeBackups
async function listRuntimeBackupsExample() {
  const camunda = createCamundaClient();

  // `prefix` must end in a single '*'. Omit it to list every backup.
  const backups = await camunda.listRuntimeBackups({ prefix: '10*' });

  for (const backup of backups) {
    console.log(`Backup ${backup.backupId}: ${backup.state}`);
  }
}
//#endregion ListRuntimeBackups

//#region GetRuntimeBackup
async function getRuntimeBackupExample() {
  const camunda = createCamundaClient();

  const backup = await camunda.getRuntimeBackup({ backupId: 100 });

  console.log(`Backup ${backup.backupId}: ${backup.state}`);
  for (const partition of backup.details) {
    console.log(`  Partition ${partition.partitionId}: ${partition.state}`);
  }
}
//#endregion GetRuntimeBackup

//#region DeleteRuntimeBackup
async function deleteRuntimeBackupExample() {
  const camunda = createCamundaClient();

  await camunda.deleteRuntimeBackup({ backupId: 100 });
}
//#endregion DeleteRuntimeBackup

//#region GetRuntimeBackupState
async function getRuntimeBackupStateExample() {
  const camunda = createCamundaClient();

  const state = await camunda.getRuntimeBackupState();

  for (const checkpoint of state.checkpointStates) {
    console.log(
      `Partition ${checkpoint.partitionId} checkpoint ${checkpoint.checkpointId} (${checkpoint.checkpointType})`
    );
  }
  for (const range of state.ranges) {
    console.log(
      `Partition ${range.partitionId} range: ${range.start?.checkpointId} -> ${range.end?.checkpointId}`
    );
  }
}
//#endregion GetRuntimeBackupState

//#region SyncRuntimeBackupState
async function syncRuntimeBackupStateExample() {
  const camunda = createCamundaClient();

  // Force-writes checkpoint and backup metadata of every partition to the backup
  // store, independent of any backup being taken, and returns the updated state.
  const state = await camunda.syncRuntimeBackupState();

  console.log(`Synced ${state.backupStates.length} partition backup states`);
}
//#endregion SyncRuntimeBackupState

//#region DeleteRuntimeBackupState
async function deleteRuntimeBackupStateExample() {
  const camunda = createCamundaClient();

  // Clears all checkpoint info, backup info, checkpoint metadata, and backup
  // ranges on every partition. Used when switching backup stores.
  await camunda.deleteRuntimeBackupState();
}
//#endregion DeleteRuntimeBackupState

// Suppress "declared but never read"
void takeRuntimeBackupExample;
void listRuntimeBackupsExample;
void getRuntimeBackupExample;
void deleteRuntimeBackupExample;
void getRuntimeBackupStateExample;
void syncRuntimeBackupStateExample;
void deleteRuntimeBackupStateExample;
