// Compilable usage examples for runtime backup operations.
// These examples are type-checked during build to guard against API regressions.

import { createCamundaClient } from '@camunda8/orchestration-cluster-api';

//#region TakeRuntimeBackup
async function takeRuntimeBackupExample() {
  const camunda = createCamundaClient();

  // Omit `backupId` when continuous backups or a backup/checkpoint schedule is
  // enabled for the physical tenant — the id is then generated by the cluster.
  // Otherwise `backupId` is required and must be higher than any existing one.
  const backup = await camunda.takeRuntimeBackup({ backupId: 100 });

  console.log(`Scheduled backup ${backup.backupId}`);
}
//#endregion TakeRuntimeBackup

//#region ListRuntimeBackups
async function listRuntimeBackupsExample() {
  const camunda = createCamundaClient();

  // `prefix` must end in a single '*'. Omit it to list every backup.
  const backups = await camunda.listRuntimeBackups({ prefix: '10*' });

  for (const backup of backups) {
    console.log(`Backup ${backup.backupId}: ${backup.state}`);
  }
}
//#endregion ListRuntimeBackups

//#region GetRuntimeBackup
async function getRuntimeBackupExample() {
  const camunda = createCamundaClient();

  const backup = await camunda.getRuntimeBackup({ backupId: 100 });

  console.log(`Backup ${backup.backupId}: ${backup.state}`);
  for (const partition of backup.details) {
    console.log(`  Partition ${partition.partitionId}: ${partition.state}`);
  }
}
//#endregion GetRuntimeBackup

//#region DeleteRuntimeBackup
async function deleteRuntimeBackupExample() {
  const camunda = createCamundaClient();

  await camunda.deleteRuntimeBackup({ backupId: 100 });
}
//#endregion DeleteRuntimeBackup

//#region GetRuntimeBackupState
async function getRuntimeBackupStateExample() {
  const camunda = createCamundaClient();

  const state = await camunda.getRuntimeBackupState();

  for (const checkpoint of state.checkpointStates) {
    console.log(
      `Partition ${checkpoint.partitionId} checkpoint ${checkpoint.checkpointId} (${checkpoint.checkpointType})`
    );
  }
  for (const range of state.ranges) {
    console.log(
      `Partition ${range.partitionId} range: ${range.start?.checkpointId} -> ${range.end?.checkpointId}`
    );
  }
}
//#endregion GetRuntimeBackupState

//#region SyncRuntimeBackupState
async function syncRuntimeBackupStateExample() {
  const camunda = createCamundaClient();

  // Force-writes checkpoint and backup metadata of every partition to the backup
  // store, independent of any backup being taken, and returns the updated state.
  const state = await camunda.syncRuntimeBackupState();

  console.log(`Synced ${state.backupStates.length} partition backup states`);
}
//#endregion SyncRuntimeBackupState

//#region DeleteRuntimeBackupState
async function deleteRuntimeBackupStateExample() {
  const camunda = createCamundaClient();

  // Clears all checkpoint info, backup info, checkpoint metadata, and backup
  // ranges on every partition. Used when switching backup stores.
  await camunda.deleteRuntimeBackupState();
}
//#endregion DeleteRuntimeBackupState

//#region TakeHistoryBackup
async function takeHistoryBackupExample() {
  const camunda = createCamundaClient();

  // Backups are logically ordered by id, so each successive backup must use a
  // higher id than the previous one.
  const backup = await camunda.takeHistoryBackup({ backupId: 100 });

  console.log(`Scheduled history backup ${backup.backupId}`);
  for (const snapshot of backup.scheduledSnapshots) {
    console.log(`  ${snapshot}`);
  }
}
//#endregion TakeHistoryBackup

//#region ListHistoryBackups
async function listHistoryBackupsExample() {
  const camunda = createCamundaClient();

  // `prefix` must end in a single '*'. Omit it to list every history backup.
  const backups = await camunda.listHistoryBackups({ prefix: '10*' });

  for (const backup of backups) {
    console.log(`History backup ${backup.backupId}: ${backup.state}`);
  }
}
//#endregion ListHistoryBackups

//#region GetHistoryBackup
async function getHistoryBackupExample() {
  const camunda = createCamundaClient();

  const backup = await camunda.getHistoryBackup({ backupId: 100 });

  // The aggregated state is derived from the state of every expected snapshot.
  console.log(`History backup ${backup.backupId}: ${backup.state}`);
}
//#endregion GetHistoryBackup

//#region DeleteHistoryBackup
async function deleteHistoryBackupExample() {
  const camunda = createCamundaClient();

  await camunda.deleteHistoryBackup({ backupId: 100 });
}
//#endregion DeleteHistoryBackup

//#region TakeHistoryBackupAsClusterAdmin
async function takeHistoryBackupAsClusterAdminExample() {
  const camunda = createCamundaClient();

  // Cluster-admin variant: fans the backup out to every physical tenant of the
  // cluster (or a single one when `physicalTenantId` is given). Requires a
  // separate cluster-admin security chain — Orchestration Cluster user
  // credentials are NOT accepted. Each backup must use a higher id than the last.
  const backup = await camunda.takeHistoryBackupAsClusterAdmin({ backupId: 100 });

  console.log(`Scheduled cluster history backup ${backup.backupId}`);
  for (const tenant of backup.physicalTenants) {
    console.log(
      `  [${tenant.physicalTenantId}] scheduled ${tenant.scheduledSnapshots.length} snapshots`
    );
  }
}
//#endregion TakeHistoryBackupAsClusterAdmin

//#region ListHistoryBackupsAsClusterAdmin
async function listHistoryBackupsAsClusterAdminExample() {
  const camunda = createCamundaClient();

  // `prefix` must end in a single '*'. Omit `physicalTenantId` to span every
  // physical tenant of the cluster — results are grouped by backup id, and each
  // group lists only the tenants that hold that id.
  const backups = await camunda.listHistoryBackupsAsClusterAdmin({ prefix: '10*' });

  for (const backup of backups) {
    console.log(`Cluster history backup ${backup.backupId}:`);
    for (const tenant of backup.physicalTenants) {
      console.log(`  [${tenant.physicalTenantId}] ${tenant.state}`);
    }
  }
}
//#endregion ListHistoryBackupsAsClusterAdmin

//#region GetHistoryBackupAsClusterAdmin
async function getHistoryBackupAsClusterAdminExample() {
  const camunda = createCamundaClient();

  // Looking a backup id up directly lists every targeted physical tenant,
  // including the ones reporting `NOT_FOUND` — a backup that only some tenants
  // hold is a supported outcome.
  const backup = await camunda.getHistoryBackupAsClusterAdmin({ backupId: 100 });

  console.log(`Cluster history backup ${backup.backupId}:`);
  for (const tenant of backup.physicalTenants) {
    console.log(`  [${tenant.physicalTenantId}] ${tenant.state}`);
  }
}
//#endregion GetHistoryBackupAsClusterAdmin

//#region DeleteHistoryBackupAsClusterAdmin
async function deleteHistoryBackupAsClusterAdminExample() {
  const camunda = createCamundaClient();

  // Deletion fans out to every physical tenant (or a single one when
  // `physicalTenantId` is given) and is not undone if a later tenant fails.
  await camunda.deleteHistoryBackupAsClusterAdmin({ backupId: 100 });
}
//#endregion DeleteHistoryBackupAsClusterAdmin

// Suppress "declared but never read"
void takeRuntimeBackupExample;
void listRuntimeBackupsExample;
void getRuntimeBackupExample;
void deleteRuntimeBackupExample;
void getRuntimeBackupStateExample;
void syncRuntimeBackupStateExample;
void deleteRuntimeBackupStateExample;
void takeHistoryBackupExample;
void listHistoryBackupsExample;
void getHistoryBackupExample;
void deleteHistoryBackupExample;
void takeHistoryBackupAsClusterAdminExample;
void listHistoryBackupsAsClusterAdminExample;
void getHistoryBackupAsClusterAdminExample;
void deleteHistoryBackupAsClusterAdminExample;
