/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  "Operate API (REST)": [
    {
      type: "autogenerated",
      dirName: "apis-tools/operate-api",
    },
  ],
};
