/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  schemaSidebar: [
    {
      type: "autogenerated",
      dirName: "apis-tools/tasklist-api",
    },
  ],
};
