/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  "Web Modeler API (REST)": [
    {
      type: "autogenerated",
      dirName: "apis-tools/web-modeler-api",
    },
  ],
};
