/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  "Tasklist API (REST)": [
    {
      type: "autogenerated",
      dirName: "apis-tools/tasklist-api-rest",
    },
  ],
};
