/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  "Administration API (SaaS)": [
    {
      type: "autogenerated",
      dirName: "apis-tools/administration-api",
    },
  ],
};
