// @ts-check

/**
 * Custom sidebar items generator for the TypeScript SDK API reference.
 *
 * The reference under `apis-tools/typescript/api-reference` is generated by
 * TypeDoc and contains ~1,900 type aliases, each as its own doc page. When a
 * sidebar category is on the active page's path, Docusaurus renders every one
 * of its siblings into that page's static HTML. With a single flat
 * "Type Aliases" category, each of the ~1,900 type-alias pages therefore
 * embeds links to all the others — an N×N blow-up that inflates this section's
 * build output to ~1.2 GB (each page ~640 KB).
 *
 * To fix this without flattening the reference into one giant page (which
 * would break every per-type deep link), we split the "Type Aliases" category
 * into fixed-size alphabetical buckets. Each type-alias page then renders only
 * its own bucket (~CHUNK_SIZE siblings) instead of all ~1,900. The pages stay
 * in the sidebar tree, so active-item highlighting and breadcrumbs keep
 * working. This drops the section's build output to ~190 MB with no change to
 * any page URL.
 *
 * Bucket size is near-optimal at ~sqrt(N): each page renders its bucket plus
 * one header per bucket, i.e. `CHUNK_SIZE + N / CHUNK_SIZE` items.
 */

const CHUNK_SIZE = 50;

/** Label of the TypeDoc-generated category this splits, from its `_category_.json`. */
const TARGET_LABEL = "Type Aliases";

/** The doc's file stem (= the type name), used for sorting and bucket labels. */
function docName(item) {
  return (item.id || item.label || "").split("/").pop();
}

function truncate(name, max = 16) {
  return name.length > max ? `${name.slice(0, max - 1)}…` : name;
}

/** Group a flat list of doc items into collapsed, alphabetically-labeled buckets. */
function bucketize(items) {
  const docs = [...items].sort((a, b) =>
    docName(a).toLowerCase().localeCompare(docName(b).toLowerCase())
  );
  const buckets = [];
  for (let i = 0; i < docs.length; i += CHUNK_SIZE) {
    const slice = docs.slice(i, i + CHUNK_SIZE);
    const first = truncate(docName(slice[0]));
    const last = truncate(docName(slice[slice.length - 1]));
    buckets.push({
      type: "category",
      label: `${first} – ${last}`,
      collapsed: true,
      items: slice,
    });
  }
  return buckets;
}

/** Recursively find the "Type Aliases" category and split it into buckets. */
function splitTypeAliases(items, state) {
  return items.map((item) => {
    if (item.type !== "category") return item;
    const children = item.items || [];
    if (item.label === TARGET_LABEL && children.length > CHUNK_SIZE) {
      state.split = true;
      return { ...item, items: bucketize(children), collapsed: true };
    }
    return { ...item, items: splitTypeAliases(children, state) };
  });
}

/**
 * Docusaurus sidebar items generator. Applies the bucketing only to the
 * TypeScript SDK API reference; every other autogenerated sidebar is returned
 * unchanged.
 */
async function tsApiSidebarItemsGenerator({
  defaultSidebarItemsGenerator,
  ...args
}) {
  const items = await defaultSidebarItemsGenerator(args);
  const dirName = args.item && args.item.dirName;
  if (dirName && dirName.includes("apis-tools/typescript/api-reference")) {
    const state = { split: false };
    const result = splitTypeAliases(items, state);
    // Without a match the N×N blow-up silently returns, so fail loudly instead.
    if (!state.split) {
      throw new Error(
        `[tsApiSidebar] No "${TARGET_LABEL}" category with more than ${CHUNK_SIZE} items found ` +
          `under "${dirName}". The TypeDoc category label likely changed; update TARGET_LABEL in ` +
          `src/tsApiSidebar.js, or remove this generator if the reference no longer needs bucketing.`
      );
    }
    return result;
  }
  return items;
}

module.exports = { tsApiSidebarItemsGenerator };
