name: Send message to Slack when a release is published
on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  slack-send:
    name: Send message to Slack
    runs-on: ubuntu-latest
    steps:
      - id: slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_ASK_C8_DOCUMENTATION }}
          webhook-type: webhook-trigger
          payload-templated: true
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "release": "${{ github.event.release.tag_name }} - ${{ github.event.release.html_url }} is going live now!"
            }
