name: Auto Assign

on:
  pull_request:
    types:
      - opened

jobs:
  add_assignees:
    if: startsWith(github.actor, 'renovate') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ github.actor }}
