name: Auto Assign

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      - opened

jobs:
  add_assignees:
    if: startsWith(github.actor, 'renovate') == false && startsWith(github.actor, 'camunda-docs-pr-automation') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
