name: Auto Assign

on:
  pull_request:
    types:
      - opened

jobs:
  add_assignees:
    if: startsWith(github.actor, 'renovate') == false && startsWith(github.actor, 'camunda-docs-pr-automation') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@a5b84af721c4a621eb9c7a4a95ec20a90d0b88e9 # v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
