name: build-docs

on: pull_request

jobs:
  build-docs:
    runs-on: gcp-core-16-default
    container: node:24
    steps:
      - uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm ci
      # Removed because it's causing build issues
      # - name: Cache Docusaurus
      #   uses: ./.github/actions/docusaurus-cache
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
