name: build-docs

on: pull_request

# If the workflow is triggered while an instance is already running,
# cancel the in-progress instance.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    # Use self-hosted runner with more resources
    runs-on: gcp-core-16-default
    permissions:
      contents: read
      id-token: write

    # The execution of a job shares the same container and resources as the runner agent
    # that communicates with GitHub. Excessive and intensive consumption of resources
    # by a job steps may starve the runner agent to the point where communication is lost,
    # forcing GitHub to consider it offline. To prevent this, we can use a separate container
    # with its own resources for the job execution.
    container: node:24

    steps:
      # SHA ref is main
      - uses: camunda/infra-global-github-actions/start-build-monitor@02b3f0e49b00b98fffc76af690ebc83c28f24dae
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Dependencies
        run: npm ci
      # Removed because it's causing build issues
      # - name: Cache Docusaurus
      #   uses: ./.github/actions/docusaurus-cache
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max-old-space-size=30720
