name: publish-prod

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "!0.25.[0-9]+"
      - "!0.26.[0-9]+"
      - "!1.0.[0-9]+"
      - "!1.1.[0-9]+"
      - "!1.2.[0-9]+"
      - "!1.3.[0-9]+"
      - "!8.0.[0-9]+"
      - "!8.1.[0-9]+"
      - "!8.2.[0-9]+"
      - "!8.3.[0-9]+"
      - "!8.4.[0-9]+"
      - "!8.5.[0-9]+"
      - "!8.6.[0-9]+"

permissions:
  id-token: write

jobs:
  publish:
    runs-on: gcp-core-16-release
    container: node:24
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci
      - name: Enable Indexing
        run: "sed -i 's/noIndex: true/noIndex: false/g' docusaurus.config.js"
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          DOCS_SITE_URL: https://docs.camunda.io
          DOCS_SITE_BASE_URL: /
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@79632e33d6953d190b940ffa440bf97821cabd80
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/camunda-docs/ci/publish PROD_PATH;
            secret/data/products/camunda-docs/ci/publish HOST;
            secret/data/products/camunda-docs/ci/publish USER;
            secret/data/products/camunda-docs/ci/publish PRIVATE_KEY;
      - name: Publish
        uses: burnett01/rsync-deployments@v9
        with:
          switches: -avzr --delete
          path: build/
          remote_path: ${{ steps.secrets.outputs.PROD_PATH }}
          remote_host: ${{ steps.secrets.outputs.HOST }}
          remote_user: ${{ steps.secrets.outputs.USER }}
          remote_key: ${{ steps.secrets.outputs.PRIVATE_KEY }}
  trigger-crawl:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@79632e33d6953d190b940ffa440bf97821cabd80
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/camunda-docs/ci/algolia-crawl API_KEY;
            secret/data/products/camunda-docs/ci/algolia-crawl APP_ID;
            secret/data/products/camunda-docs/ci/algolia-crawl CRAWLER_NAME;
            secret/data/products/camunda-docs/ci/algolia-crawl CRAWLER_API_KEY;
            secret/data/products/camunda-docs/ci/algolia-crawl CRAWLER_USER_ID;
      - name: Trigger Algolia crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.13
        id: algolia_crawler
        with:
          crawler-user-id: ${{ steps.secrets.outputs.CRAWLER_USER_ID }}
          crawler-api-key: ${{ steps.secrets.outputs.CRAWLER_API_KEY }}
          algolia-app-id: ${{ steps.secrets.outputs.APP_ID }}
          algolia-api-key: ${{ steps.secrets.outputs.API_KEY }}
          site-url: "https://docs.camunda.io"
          crawler-name: ${{ steps.secrets.outputs.CRAWLER_NAME }}
