name: publish-stage

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

permissions:
  id-token: write

jobs:
  publish:
    runs-on: gcp-core-8-default
    container: node:24
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci
      - name: Cache Docusaurus
        uses: ./.github/actions/docusaurus-cache
      - name: Update redirects for environment
        run: "sed -i 's!https://unsupported.docs.camunda.io!https://stage.unsupported.docs.camunda.io!g' ./static/.htaccess"
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          DOCS_SITE_URL: https://stage.docs.camunda.io
          DOCS_SITE_BASE_URL: /
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@79632e33d6953d190b940ffa440bf97821cabd80
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/camunda-docs/ci/publish STAGE_PATH;
            secret/data/products/camunda-docs/ci/publish HOST;
            secret/data/products/camunda-docs/ci/publish USER;
            secret/data/products/camunda-docs/ci/publish PRIVATE_KEY;
      - name: Publish
        uses: burnett01/rsync-deployments@v9
        with:
          switches: -avzr --delete
          path: build/
          remote_path: ${{ steps.secrets.outputs.STAGE_PATH }}
          remote_host: ${{ steps.secrets.outputs.HOST }}
          remote_user: ${{ steps.secrets.outputs.USER }}
          remote_key: ${{ steps.secrets.outputs.PRIVATE_KEY }}
  notify-failure:
    name: Send message to Slack on failure
    runs-on: ubuntu-latest
    needs:
      - publish
    if: failure()
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@79632e33d6953d190b940ffa440bf97821cabd80
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/camunda-docs/ci/slack DOCS_NOTIFICATION_WEBHOOK_URL;
      - id: slack
        uses: slackapi/slack-github-action@e090a7a7c0b2d9b7ae32bd34f086e680ce260b06
        with:
          webhook: ${{ steps.secrets.outputs.DOCS_NOTIFICATION_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload-templated: true
          payload: |
            {
              "github_server_url": "${{ github.server_url }}",
              "github_repo": "${{ github.repository }}",
              "github_run_id": "${{ github.run_id }}",
              "github_ref_name": "${{ github.ref_name }}",
              "github_workflow": "${{ github.workflow }}"
            }
